name: Publish Olive Generator Package

on:
  push:
    branches: [ master ]

jobs:
 build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
    - name: Publish Olive Data End Point Generator Package
      run: dotnet pack -c Release -o . DataEndPointGenerator/Olive.DataEndPointGenerator.csproj
    - name: Publish
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
